# Generated by Django 4.2.16 on 2025-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german', models.CharField(max_length=200)),
                ('turkish', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=200)),
            ],
        ),
    ]
