# Generated by Django 4.2.16 on 2025-02-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='image_path',
            new_name='image_name',
        ),
    ]
