# Generated by Django 4.2.16 on 2025-02-22 17:30
import csv
import os

from django.db import migrations

def load_cards_from_csv(apps, schema_editor):
    Card = apps.get_model('cards', 'Card') 

    csv_file_path = os.path.join(os.path.dirname(__file__), 'cards.csv') # Path relative to migration file.

    try:
        with open(csv_file_path, 'r', encoding='utf-8') as csvfile: # handle encoding
            reader = csv.DictReader(csvfile)
            cards_to_insert = []
            for row in reader:
                try:
                    card = Card(
                        german=row['german'],
                        turkish=row['turkish'],
                        image_name=row['image_name'],
                    )
                    cards_to_insert.append(card)
                except KeyError as e:
                    print(f"Error processing row: {row}. Missing column: {e}")
                except Exception as e: # Catch other potential errors
                    print(f"Error processing row: {row}. Error: {e}")

            if cards_to_insert: # check if any cards were created
                Card.objects.bulk_create(cards_to_insert)
            else:
                print("No valid cards found in CSV file.")

    except FileNotFoundError:
        print(f"CSV file not found at: {csv_file_path}")
    except Exception as e:
        print(f"An error occurred while reading the CSV file: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_cards_from_csv),
    ]
